### ISSUE TITLE
Implement easy-breezy API for constructing bem-string

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk/bem-sdk#165]
Possible candidate:

```
import b from '@bem/naming';

b('button2')('text') // button2__text
b('popup') // popup
b('popup)({theme: normal}) // popup_theme_normal
```

**Comment by zxqfox** [comment]
```js
import { carrier } from '@bem/naming';

carrier('button2')('text')...
```

**Comment by skad0** [comment]
carrier? seems wild unexpected

**Comment by skad0** [comment]
```js
b('button2').e('text').m({ theme: 'norma' })
```
As for me looks easier for reading and understading.

**Comment by zxqfox** [comment]
```
import { b_ } from '@bem/naming';
const b_ = require('@bem/naming/b_');

b_('button2')('text')...
```

**Comment by awinogradov** [comment]
I want!) World is ready to this magic)

I like @skad0 implementation:
``` js
b('button2').e('text').m({ theme: 'normal' })
```

Also, would be great add mix helper:
``` js
const b1 = b('button2').e('text').m({ theme: 'normal', size: 'm' });
const b2 = b('sharik').e('palka').m({ dva: 'struna' });

b('dagestan').m({ moya: 'strana' }).mix(b1, b2);
```

**Comment by awinogradov** [comment]
https://gist.github.com/awinogradov/8ca52fd3364486fe46791a7387fd550b

**Comment by Yeti-or** [comment]
@awinogradov let's make it part of `@bem/naming` as
@zxqfox suggested

**Comment by awinogradov** [comment]
I've made temporary package [easy-bem-naming](https://github.com/awinogradov/easy-bem-naming) for testing this kind API. We'll try to use it in the [bem-react-core](https://github.com/bem/bem-react-core) and then we can implement it here in `bem-naming` with stable API.
